services:
    postgres:
        image: postgres:17-alpine
        container_name: postgress
        environment:
            #POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            #POSTGRES_DB: test
    
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        ports:
            - "8888:80"
        environment:
          PGADMIN_DEFAULT_EMAIL: wojtekdxd@gmail.com
          PGADMIN_DEFAULT_PASSWORD: admin

    qdrant:
        image: qdrant/qdrant
        container_name: qdrant
        ports:
            - "6333:6333"