services:
    postgres:
        image: postgres:17-alpine
        container_name: postgress
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
#        ports:
#            - "5432:5432"
        volumes:
            - ./postgres_db/dump.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 2s
            timeout: 5s
            retries: 5
    
#    pgadmin:
#        image: dpage/pgadmin4
#        container_name: pgadmin
#        ports:
#            - "8888:80"
#        environment:
#          PGADMIN_DEFAULT_EMAIL:
#          PGADMIN_DEFAULT_PASSWORD: admin

    qdrant:
        image: qdrant/qdrant
        container_name: qdrant
        ports:
            - "6333:6333"

    django:
        build:
            context: ./db_api
        container_name: django_api
        depends_on:
            postgres:
                condition: service_healthy
        volumes:
            - ./db_api:/app
        ports:
            - "8000:8000"
        environment:
            POSTGRES_DB: restaurant_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_HOST: postgress
            POSTGRES_PORT: 5432