from .shared import IDENTITY, ADDITIONAL_GUARDRAILS
from .primary import PRIMARY_EXAMPLES, PRIMARY_INFORMATION, PRIMARY_PROMPT
from .orders import ORDER_PROMPT, ORDER_INSTRUCTIONS
from .menu import MENU_PROMPT
